[package]
name = "chatgpt-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.5.0"
getopts = "0.2.21"
rustyline = "10.0.0"
serde = "1.0.152"
serde_json = "1.0.91"
tokio = { version = "1", features = ["full"] }
