[package]
name = "chatgpt-repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-openai = "0.5.0"
async-trait = "0.1.61"
getopts = "0.2.21"
rustyline = "10.0.0"
serde = "1.0.152"
serde_json = "1.0.91"
spinoff = "0.6.0"
tokio = { version = "1", features = ["full"] }
