[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.install]
command = "install"
args = ["target/release/chatgpt-repl", "~/.local/bin"]
dependencies = ["build"]
